Repository smileeeeely/nextflix, pull requests merged in 2025-03, with the labels that each got.

#6 chore:#5 레이아웃 기본 설정 및 이미지 포맷 설정
  next.config.mjs
  src/app/layout.tsx
  src/app/page.tsx
Labels: ⚙ Setting

#7 Feature/#2 intro page
  src/app/page.tsx
Labels: ✨ Feature

#14 Feature/#3 category UI
  src/app/category/page.tsx
  src/app/globals.css
  src/app/not-found.tsx
  src/components/category/CategorySection.tsx
  src/constants/movieCategory.ts
  src/services/movieCategory.ts
  src/types/Movie.ts
Labels: 📬 API, ✨ Feature, 🎨 Styles

#25 Feature/#20 card 컴포넌트 및 UI
  components.json
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/app/loading.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/components/commons/LoadingSpinner.tsx
  src/components/commons/MovieCard.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/lib/utils.ts
  src/libs/utils.ts
  tailwind.config.ts
Labels: ✨ Feature, ⚙ Setting, 🎨 Styles

#23 Feature/#8 search page
  public/images/noImage.png
  src/app/api/search/route.ts
  src/app/search/page.tsx
  src/constants/movieCategory.ts
  src/services/searchMovie.ts
  tsconfig.json
Labels: 📬 API, ✨ Feature

#21 Feature/#10 영화 상세 api
  src/app/detail/[id]/page.tsx
  src/components/detail/Info.tsx
  src/components/detail/LinkBtn.tsx
  src/constants/movieVideoUrl.ts
  src/constants/tmdbConstants.ts
  src/services/serviceMovieDetails.ts
  src/types/Video.ts
Labels: 📬 API, ✨ Feature

#26 Refactor#22 카테고리 UI
  pnpm-lock.yaml
  src/app/category/(detail)/layout.tsx
  src/app/category/(detail)/now-playing/[page]/page.tsx
  src/app/category/(detail)/popular/[page]/page.tsx
  src/app/category/(detail)/top-rated/[page]/page.tsx
  src/app/category/(detail)/upcoming/[page]/page.tsx
  src/app/globals.css
  src/components/back-button.tsx
  src/components/pageNationBtn.tsx
  src/components/ui/badge.tsx
  src/constants/movieCategory.ts
  src/services/category/serverApi.ts
Labels: 🔨 Refactor, 🎨 Styles

#28 Feature/#11 댓글 기능 구현
  pnpm-lock.yaml
  src/app/detail/[id]/page.tsx
  src/components/commons/Header.tsx
  src/components/detail/Info.tsx
  src/components/detail/InputComment.tsx
  src/components/detail/MovieComments.tsx
  src/components/ui/button.tsx
  src/components/ui/textarea.tsx
  src/services/detail/serviceComments.ts
  src/types/Comment.ts
  src/utils/formatFunction.ts
Labels: 📬 API, ✨ Feature, 🔨 Refactor, 🎨 Styles

#31 Feature#27 sign in Page
  package.json
  pnpm-lock.yaml
  src/app/sign-in/page.tsx
  src/components/commons/Header.tsx
  src/components/commons/SignInForm.tsx
  src/services/signIn.ts
  src/store/useAuthStore.ts
Labels: ✨ Feature

#30 Feature/#24 회원가입 구현
  package.json
  pnpm-lock.yaml
  src/app/sign-up/page.tsx
  src/constants/signUp.ts
  src/hooks/useSignUpSchema.ts
  src/services/signUpSupabase.ts
Labels: ✨ Feature

#34 Feature/#29 bookmark UI
  src/app/detail/[id]/page.tsx
  src/app/globals.css
  src/components/detail/BookmarkBtn.tsx
  src/components/ui/button.tsx
Labels: 🎨 Styles

#33 Refactor/#18 Home
  src/app/category/page.tsx
  src/app/home/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/category/CategorySection.tsx
  src/components/commons/MovieCard.tsx
  src/components/commons/ScoreDonut.tsx
  src/components/detail/MovieComments.tsx
  src/components/home/CategorySection.tsx
  src/components/home/SkeletoneCard.tsx
  src/components/home/SkeletoneList.tsx
  src/components/ui/card.tsx
  src/services/movieCategory.ts
  src/utils/formatFunction.ts
  src/utils/getScoreColor.ts
Labels: 🔨 Refactor

#44 Chore:#42 react-intersection-observer 설치
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting

#37 Feature/#29 bookmark api
  src/app/detail/[id]/page.tsx
  src/components/detail/BookmarkBtn.tsx
  src/services/detail/serviceBookmarks.ts
  src/types/Bookmark.ts
Labels: 📬 API, ✨ Feature

#41 Feature#36 sign in 토큰 유효성 검증
  src/app/sign-in/page.tsx
  src/components/commons/SignInForm.tsx
  src/services/signIn.ts
  src/store/useAuthStore.ts
Labels: ✨ Feature, 🔨 Refactor, ⚙ Setting

#42 Refactor/#40 alert 구현
  package.json
  pnpm-lock.yaml
  src/components/commons/ErrorAlert.tsx
  src/constants/alertType.ts
  src/lib/openAlert.ts
Labels: ✨ Feature, 🎨 Styles

#45 Refactor/#39 중복 타입 수정
  pnpm-lock.yaml
  src/app/category/(detail)/now-playing/[page]/page.tsx
  src/app/category/(detail)/popular/[page]/page.tsx
  src/app/category/(detail)/top-rated/[page]/page.tsx
  src/app/category/(detail)/upcoming/[page]/page.tsx
  src/app/detail/[id]/page.tsx
  src/services/category/serverApi.ts
  src/types/DetailMovie.ts
  src/types/category/movie.ts
Labels: 🔨 Refactor

#48 Refactor/#39 중복 api service 수정
  src/app/detail/[id]/page.tsx
  src/app/search/page.tsx
  src/components/commons/MovieCard.tsx
  src/components/detail/Info.tsx
  src/constants/movieCategory.ts
  src/constants/tmdbBaseUrl.ts
  src/constants/tmdbConstants.ts
  src/services/serviceMovieDetails.ts
Labels: 🔨 Refactor

#51 Refactor/#38 사용자 정보 연결
  src/app/detail/[id]/page.tsx
  src/components/detail/BookmarkBtn.tsx
  src/components/detail/InputComment.tsx
  src/components/detail/MovieComments.tsx
  src/store/useAuthStore.ts
Labels: 🔨 Refactor, 🎨 Styles

#53 Feature/#32 search infinite scroll
  pnpm-lock.yaml
  src/app/Provider.tsx
  src/app/api/search/route.ts
  src/app/layout.tsx
  src/app/search/page.tsx
  src/constants/tmdbBaseUrl.ts
  src/services/searchMovie.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Styles

#54 Feature/#19 마이페이지 기능 구현
  src/app/my-page/page.tsx
  src/components/commons/MovieCard.tsx
  src/components/detail/Info.tsx
  src/utils/supabaseClient.ts
Labels: ✨ Feature

#58 Refactor/#52 detail page 수정
  src/app/detail/[id]/page.tsx
  src/components/detail/BookmarkBtn.tsx
  src/components/detail/Info.tsx
  src/components/detail/InputComment.tsx
  src/components/detail/LinkBtn.tsx
  src/components/detail/MovieComments.tsx
  src/services/detail/serviceBookmarks.ts
  src/services/detail/serviceComments.ts
  src/services/serviceMovieDetails.ts
  src/utils/formatFunction.ts
  src/utils/supabaseClient.ts
Labels: ✨ Feature, 🔨 Refactor

#62 Refactor/#57 update constants
  src/app/category/(detail)/now-playing/[page]/page.tsx
  src/app/category/(detail)/popular/[page]/page.tsx
  src/app/category/(detail)/top-rated/[page]/page.tsx
  src/app/category/(detail)/upcoming/[page]/page.tsx
  src/app/home/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/sign-in/page.tsx
  src/app/sign-up/page.tsx
  src/components/commons/Header.tsx
  src/components/commons/SignInForm.tsx
  src/components/detail/LinkBtn.tsx
  src/components/detail/WrapperBox.tsx
  src/components/layout/MoviesSearch.tsx
  src/constants/movieCategory.ts
  src/constants/pagePath.ts
  src/hooks/useAuthListner.ts
Labels: 🔨 Refactor

#64 Hotfix/#60-에러-페이지-적용
  src/app/detail/[id]/error.tsx
  src/app/detail/[id]/page.tsx
  src/components/commons/ErrorAlert.tsx
Labels: 🔨 Refactor, 🎨 Styles

#66 chore:#65 eslint 다운그레이드
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting

#68 fix:#67 빌드 에러 해결
  .eslintrc.json
  src/app/detail/[id]/error.tsx
  src/components/detail/BookmarkBtn.tsx
  src/components/detail/InputComment.tsx
  src/components/detail/MovieComments.tsx
  src/hooks/useAuthListner.ts
  src/services/detail/serviceBookmarks.ts
  src/services/signIn.ts
  src/store/useAuthStore.ts
Labels: 🐞 BugFix

#70 Refactor:#69 fetch searchMovie url 변경 및 카드 컴포넌트 수정
  src/components/commons/MovieCard.tsx
  src/services/searchMovie.ts
Labels: 🔨 Refactor

#73 Docs/#71-ReadME
  README.md
Labels: 📃 Docs

#77 Refactor/#56 마이페이지 리팩토링
  src/app/my-page/page.tsx
  src/components/layout/UserMenu.tsx
  src/components/my-page/BookmarkList.tsx
  src/components/my-page/ProfileSection.tsx
  src/components/ui/input.tsx
  src/constants/pagePath.ts
  src/utils/supabaseClient.ts
Labels: 🔨 Refactor, 🎨 Styles

#72 Feature#47 토큰 만료 갱신
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/Provider.tsx
  src/components/appLayout.tsx
  src/components/commons/SignInForm.tsx
  src/components/layout/UserMenu.tsx
  src/hooks/useAuthListener.ts
  src/hooks/useAuthListner.ts
  src/services/signIn.ts
Labels: ✨ Feature, ⚙ Setting

#79 Refactor/#63 search and signup
  src/app/page.tsx
  src/app/search/page.tsx
  src/app/sign-up/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/services/searchMovie.ts
  src/services/signUpSupabase.ts
Labels: 🔨 Refactor

#74 Refactor#55 category 로직 리팩토링
  pnpm-lock.yaml
  src/app/category/layout.tsx
  src/app/category/now-playing/[page]/page.tsx
  src/app/category/popular/[page]/page.tsx
  src/app/category/top-rated/[page]/page.tsx
  src/app/category/upcoming/[page]/page.tsx
  src/app/home/page.tsx
  src/app/sign-in/page.tsx
  src/components/appLayout.tsx
  src/components/category/pageNationBtn.tsx
  src/components/commons/SignInForm.tsx
  src/constants/signUp.ts
  src/services/category/serverApi.ts
  src/services/signIn.ts
Labels: 🔨 Refactor

#76 Refactor#75 로그인-로그아웃 설정 / 로그인-회원가입 폼 통일
  src/app/Provider.tsx
  src/app/sign-up/page.tsx
  src/hooks/useAuthListener.ts
Labels: 🥰 Accessibility, 🔨 Refactor, 🎨 Styles

#78 Refactor/#61 movie card
  pnpm-lock.yaml
  src/app/detail/[id]/page.tsx
  src/components/commons/MovieCard.tsx
  src/components/detail/WrapperBox.tsx
  src/components/layout/Header.tsx
Labels: 🎨 Styles
